### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by lixian5968** [luoyesiqiu/dpt-shell#10]
hook LoadMethod 之后，dex_file的指针为什么要往后移动begin_offset位？
begin_ 应该是dex_file.h 下面的第一个属性值吧？

这行代码

uint8_t **begin_ptr = (uint8_t **) ((uint8_t *) dex_file + begin_offset);

**Comment by luoyesiqiu** [comment]
是的，加上偏移是为了定位到**begin_**字段

**Comment by lixian5968** [comment]
打扰下，为什么有这个偏移 begin_offset ？
按照dex_file.h的结构，begin_offset  应该为0才对吧 ？

**Comment by luoyesiqiu** [comment]
它开头有虚表指针
