### ISSUE TITLE
为什么加固完apk重新签名之后闪退

### ISSUE THREAD

**Issue by wawls** [luoyesiqiu/dpt-shell#18]

**Comment by luoyesiqiu** [comment]
麻烦提供一下apk

**Comment by wawlsl** [comment]
基本我测试的所有软件都如此 我大概描述一下 加固完apk后不重新打包可以正常进去
但似乎一旦对apk重打包就无法进入

> 麻烦提供一下APK

**Comment by luoyesiqiu** [comment]
重打包是在里面加入一些自己的dex或者自己的so吗？

**Comment by wawlsl** [comment]
> 重打包是在里面加入一些自己的dex或者自己的so吗？
更改签名或其他一些

**Comment by wawlsl** [comment]
可修复此问题吗

**Comment by luoyesiqiu** [comment]
试了一下，这是二次打包生成的zip没法解压导致的，这边看一下怎么处理这个问题

**Comment by luoyesiqiu** [comment]
已解决
