### ISSUE TITLE
加壳后，Apk的部分功能出现异常

### ISSUE THREAD

**Issue by githubXiaowangzi** [luoyesiqiu/dpt-shell#19]
这里是样本-原apk的下载地址，https://wwyr.lanzoue.com/ivoyD0s7gjzg
使用加壳后的apk处理别的apk时，报错：orgjf.dexlib2.analysis.UnresolvedClassException: Could not resolve class Lcom/apksignaturekiller/HookApplication;

**Comment by luoyesiqiu** [comment]
这个apk强依赖classes.dex，目前的加固方式没办法使他正常运行。如果想正常使用只能用1.4.0以前的版本，并把HookApplication类加到exclude列表。
