### ISSUE TITLE
请问不用禁用dex2oat吗？

### ISSUE THREAD

**Issue by Sp1keeeee** [luoyesiqiu/dpt-shell#2]
如果编译生成了quick code不就直接执行quick code 而不会进入解释模式执行回填的代码了吗？
或者说是不是由于指令都被抽空了 然后安装apk的时候系统就不会编译生成oat代码了，所以就不用禁用dex2oat了？

**Comment by luoyesiqiu** [comment]
系统还是会生成oat的，所以我的理解是还是得禁用oat，现在还没去研究怎么禁用或者不使用oat代码。
