### ISSUE TITLE
Android10闪退，日志如下,似乎调用init时出现错误，加固前后apk放最后

### ISSUE THREAD

**Issue by SummerflyAndIce** [luoyesiqiu/dpt-shell#23]
BaseActivity:     [BaseActivity] QuickstepAppTransitionManagerImpl.java, onAnimationStart, line: 158
Foreground_io: Done
OpPowerConsumpStatsInjector: notifyPkgEvent
RampAnimator: mRate:4 mDelta:-37 mCurrentValue:225
dpt ProxyComponentFactory: instantiateClassLoader() called with: cl = [dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/lib/arm64, /data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]]], aInfo = [ApplicationInfo{8e2a644 com.example.myapplication}]
dpt_native: init_dpt call!
bytehook_tag: bytehook init, mode 0, debug 0, return 0
dpt_native: mmap hook success!
sensors-hal: GetBrightnessEventCallback:146, brightness : 225
dpt_native: getOatDexFile symbol = _ZNK3art7OatFile13GetOatDexFileEPKcPKjPNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE

libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x769e46d008 in tid 32443 (e.myapplication), pid 32443 (e.myapplication)
crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
/system/bin/tombstoned: received crash request for pid 32443
crash_dump64: performing dump of process 32443 (target tid = 32443)
DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
DEBUG   : Build fingerprint: 'OnePlus/OnePlus7TPro/OnePlus7TPro:10/QKQ1.190716.003/2009281542:user/release-keys'
DEBUG   : Revision: '0'
DEBUG   : ABI: 'arm64'
DEBUG   : Timestamp: 2023-05-22 20:28:35+0800
DEBUG   : pid: 32443, tid: 32443, name: e.myapplication  >>> com.example.myapplication <<<
DEBUG   : uid: 10339
DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x769e46d008
DEBUG   : Cause: execute-only (no-read) memory access error; likely due to data in .text.
DEBUG   :     x0  0000000000000001  x1  0000000000000020  x2  000000769f9374c0  x3  0000000000000001
DEBUG   :     x4  0000000000000000  x5  0000007ff6dd3768  x6  9104d231f0cf4411  x7  d61f02209104d231
DEBUG   :     x8  000000763cd4d0a8  x9  000000763cd4cd48  x10 000000000000003d  x11 00000000ffffffff
DEBUG   :     x12 000000000000000d  x13 0000000000004a80  x14 0000000000000010  x15 aaaaaaaaaaaaaaab
DEBUG   :     x16 00000077235e3768  x17 00000077235d7350  x18 0000007725394000  x19 000000769f9374c0
DEBUG   :     x20 000000769e46d008  x21 000000769e46d008  x22 000000769f9be6a0  x23 000000772606bcb6
DEBUG   :     x24 0000007726075203  x25 000000769e46d014  x26 000000003b000000  x27 0000000018000000
DEBUG   :     x28 00000000f2a00000  x29 0000000010000000
DEBUG   :     sp  0000007ff6dd3750  lr  000000763cd0d9f4  pc  000000763cd0da4c
DEBUG   :
DEBUG   : backtrace:
DEBUG   :       #00 pc 000000000003ca4c  /data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk!libdpt.so (offset 0x187000) (BuildId: ab4f4d5f8b7ddd376499719873860edc4ee63ca4)
DEBUG   :       #01 pc 0000000000038fb4  /data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk!libdpt.so (offset 0x187000) (BuildId: ab4f4d5f8b7ddd376499719873860edc4ee63ca4)
DEBUG   :       #02 pc 0000000000038470  /data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk!libdpt.so (offset 0x187000) (DobbyHook+164) (BuildId: ab4f4d5f8b7ddd376499719873860edc4ee63ca4)
DEBUG   :       #03 pc 000000000001cce0  /data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk!libdpt.so (offset 0x187000) (BuildId: ab4f4d5f8b7ddd376499719873860edc4ee63ca4)
DEBUG   :       #04 pc 0000000000052358  /apex/com.android.runtime/bin/linker64 (__dl__ZL10call_arrayIPFviPPcS1_EEvPKcPT_mbS5_+276) (BuildId: 57c25d8dc24179d73f5254df54b80f81)
DEBUG   :       #05 pc 0000000000052574  /apex/com.android.runtime/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+376) (BuildId: 57c25d8dc24179d73f5254df54b80f81)
DEBUG   :       #06 pc 000000000003cc34  /apex/com.android.runtime/bin/linker64 (__dl__Z9do_dlopenPKciPK17android_dlextinfoPKv+2416) (BuildId: 57c25d8dc24179d73f5254df54b80f81)
DEBUG   :       #07 pc 00000000000380dc  /apex/com.android.runtime/bin/linker64 (__loader_android_dlopen_ext+72) (BuildId: 57c25d8dc24179d73f5254df54b80f81)
DEBUG   :       #08 pc 00000000000010b8  /apex/com.android.runtime/lib64/bionic/libdl.so (android_dlopen_ext+12) (BuildId: 085667b47b7af30e22612c43c624b87c)
DEBUG   :       #09 pc 0000000000007fd8  /apex/com.android.runtime/lib64/libnativeloader.so (OpenNativeLibraryInNamespace+128) (BuildId: 25a2a21da52d49618cd69a099a0a7379)
DEBUG   :       #10 pc 0000000000007c5c  /apex/com.android.runtime/lib64/libnativeloader.so (OpenNativeLibrary+200) (BuildId: 25a2a21da52d49618cd69a099a0a7379)
DEBUG   :       #11 pc 000000000037b938  /apex/com.android.runtime/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*)+2032) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #12 pc 00000000000050e0  /apex/com.android.runtime/lib64/libopenjdkjvm.so (JVM_NativeLoad+412) (BuildId: 4a9dc3cebf837d6dcf62939caf9995ad)
DEBUG   :       #13 pc 00000000000b9af4  /system/framework/arm64/boot.oat (art_jni_trampoline+228) (BuildId: 641fa046761807124c6c1e1e7192ad5e052b8af3)
DEBUG   :       #14 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #15 pc 000000000014600c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #16 pc 00000000002e3948  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #17 pc 00000000002deba8  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+892) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #18 pc 00000000005a3c08  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+372) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #19 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #20 pc 00000000000e3dd2  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.Runtime.nativeLoad+2)
DEBUG   :       #21 pc 00000000005a3ea4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1040) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #22 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #23 pc 00000000000e42d6  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.Runtime.loadLibrary0+46)
DEBUG   :       #24 pc 00000000005a3700  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1100) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #25 pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #26 pc 00000000000e4290  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.Runtime.loadLibrary0+8)
DEBUG   :       #27 pc 00000000005a13f4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #28 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #29 pc 00000000000e9834  /apex/com.android.runtime/javalib/core-oj.jar (java.lang.System.loadLibrary+16)
DEBUG   :       #30 pc 00000000005a3ea4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1040) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #31 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #32 pc 0000000000002ee0  /data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk (com.luoyesiqiu.shell.JniBridge.<clinit>+20)
DEBUG   :       #33 pc 00000000002b4c5c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12938883504528282530+240) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #34 pc 000000000059269c  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1032) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #35 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #36 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #37 pc 000000000014600c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #38 pc 00000000001723b4  /apex/com.android.runtime/lib64/libart.so (art::ClassLinker::InitializeClass(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+2312) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #39 pc 000000000015ced8  /apex/com.android.runtime/lib64/libart.so (art::ClassLinker::EnsureInitialized(art::Thread*, art::Handle<art::mirror::Class>, bool, bool)+92) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #40 pc 00000000002e39dc  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+532) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #41 pc 00000000002deba8  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+892) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #42 pc 00000000005a3c08  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+372) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #43 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #44 pc 0000000000003660  /data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk (com.luoyesiqiu.shell.ProxyComponentFactory.init+16)
DEBUG   :       #45 pc 00000000005a3700  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1100) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #46 pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #47 pc 00000000000037ce  /data/app/com.example.myapplication-LNI4HvG3NLp0EZVKMAuIAg==/base.apk (com.luoyesiqiu.shell.ProxyComponentFactory.instantiateClassLoader+70)
DEBUG   :       #48 pc 00000000005a13f4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #49 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #50 pc 00000000001fe632  /system/framework/framework.jar (android.app.LoadedApk.createOrUpdateClassLoaderLocked+1382)
DEBUG   :       #51 pc 00000000005a3700  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1100) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #52 pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #53 pc 00000000001fdbb4  /system/framework/framework.jar (android.app.LoadedApk.getClassLoader+12)
DEBUG   :       #54 pc 00000000005a13f4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #55 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #56 pc 00000000001fda1e  /system/framework/framework.jar (android.app.LoadedApk.getResources+58)
DEBUG   :       #57 pc 00000000005a13f4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #58 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #59 pc 00000000001ac48a  /system/framework/framework.jar (android.app.ContextImpl.createAppContext+34)
DEBUG   :       #60 pc 00000000005a3ea4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1040) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #61 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #62 pc 00000000001ac44e  /system/framework/framework.jar (android.app.ContextImpl.createAppContext+2)
DEBUG   :       #63 pc 00000000005a3ea4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1040) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #64 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #65 pc 000000000018cbdc  /system/framework/framework.jar (android.app.ActivityThread.handleBindApplication+1700)
DEBUG   :       #66 pc 00000000005a3700  /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1100) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #67 pc 0000000000131914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #68 pc 0000000000189cb4  /system/framework/framework.jar (android.app.ActivityThread.access$1700)
DEBUG   :       #69 pc 00000000005a3ea4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1040) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #70 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #71 pc 0000000000185f82  /system/framework/framework.jar (android.app.ActivityThread$H.handleMessage+1474)
DEBUG   :       #72 pc 00000000005a13f4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #73 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #74 pc 000000000030664a  /system/framework/framework.jar (android.os.Handler.dispatchMessage+38)
DEBUG   :       #75 pc 00000000005a13f4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1352) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #76 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #77 pc 000000000032b502  /system/framework/framework.jar (android.os.Looper.loop+466)
DEBUG   :       #78 pc 00000000005a3ea4  /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+1040) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #79 pc 0000000000131994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #80 pc 0000000000190ddc  /system/framework/framework.jar (android.app.ActivityThread.main+196)
DEBUG   :       #81 pc 00000000002b4c5c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12938883504528282530+240) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #82 pc 000000000059269c  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1032) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #83 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #84 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #85 pc 000000000014600c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #86 pc 00000000004b103c  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #87 pc 00000000004b2be0  /apex/com.android.runtime/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1480) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #88 pc 000000000043df14  /apex/com.android.runtime/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #89 pc 00000000000c2c34  /system/framework/arm64/boot.oat (art_jni_trampoline+180) (BuildId: 641fa046761807124c6c1e1e7192ad5e052b8af3)
DEBUG   :       #90 pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #91 pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #92 pc 00000000002e3948  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #93 pc 00000000002deba8  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+892) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #94 pc 00000000005a1134  /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+648) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #95 pc 0000000000131814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #96 pc 00000000003688d6  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
DEBUG   :       #97 pc 00000000002b4c5c  /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12938883504528282530+240) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #98 pc 000000000059269c  /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1032) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #99 pc 0000000000140468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #100 pc 00000000009d4f50  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2256) (BuildId: 6a67096a4e592d7647523a2c8839cabd9024ccc6)
DEBUG   :       #101 pc 00000000001375b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #102 pc 000000000014600c  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+276) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #103 pc 00000000004b103c  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #104 pc 00000000004b0c2c  /apex/com.android.runtime/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+408) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #105 pc 00000000003bb718  /apex/com.android.runtime/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+624) (BuildId: ced0e918261ca872f5cff4cdba80b1a9)
DEBUG   :       #106 pc 00000000000c099c  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116) (BuildId: be5a9855df93a95dcfdd488bd8622eac)
DEBUG   :       #107 pc 00000000000c3900  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+988) (BuildId: be5a9855df93a95dcfdd488bd8622eac)
DEBUG   :       #108 pc 00000000000035b0  /system/bin/app_process64 (main+1376) (BuildId: 33a1e691b72e968a5f2d9505175e377f)
DEBUG   :       #109 pc 000000000006ebc4  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: a2584ee8458a61d422edf24b4cd23b78)
adbd    : failed to connect to socket 'tcp:6666': Connection refused
chatty  : uid=1000(system) PowerManagerSer identical 21 lines
RampAnimator: mRate:4 mDelta:-37 mCurrentValue:225
RampAnimator: mRate:4 mDelta:-37 mCurrentValue:224
sensors-hal: GetBrightnessEventCallback:146, brightness : 224
chatty  : uid=1000(system) PowerManagerSer identical 3 lines
RampAnimator: mRate:4 mDelta:-37 mCurrentValue:224
ActivityTaskManager:   Force finishing activity com.example.myapplication/.MainActivity
DropBoxManagerService: add tag=data_app_native_crash isTagEnabled=true flags=0x2
/system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_00
ScreenModeService: getAppToken AppWindowToken{a52d37f token=Token{11ac9e ActivityRecord{f13cad9 u0 net.oneplus.launcher/.Launcher t223}}}
ScreenModeService: setRefreshRate token AppWindowToken{a52d37f token=Token{11ac9e ActivityRecord{f13cad9 u0 net.oneplus.launcher/.Launcher t223}}} rate 0
OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{a52d37f token=Token{11ac9e ActivityRecord{f13cad9 u0 net.oneplus.launcher/.Launcher t223}}} pkgName net.oneplus.launcher
OpSlaNetlinkHelper: frontPackageChanged: net.oneplus.launcher uid:10142 pid:26097 | com.example.myapplication uid:10339 pid:32443
FrameworkEventCollector: recordAppIssue PN: com.example.myapplication
ScreenModeService: getAppToken AppWindowToken{a52d37f token=Token{11ac9e ActivityRecord{f13cad9 u0 net.oneplus.launcher/.Launcher t223}}}
ScreenModeService: setRefreshRate token AppWindowToken{a52d37f token=Token{11ac9e ActivityRecord{f13cad9 u0 net.oneplus.launcher/.Launcher t223}}} rate 0
OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{a52d37f token=Token{11ac9e ActivityRecord{f13cad9 u0 net.oneplus.launcher/.Launcher t223}}} pkgName net.oneplus.launcher
BootReceiver: Copying /data/tombstones/tombstone_00 to DropBox (SYSTEM_TOMBSTONE)
PackageManager.DexOptimizer: profile size is too small, do nothing.
DropBoxManagerService: add tag=SYSTEM_TOMBSTONE isTagEnabled=true flags=0x2
OPDOM   : performDexOpt end for com.example.myapplication sucessed: false
cpe     : OS Event: crash
[归档.zip](https://github.com/luoyesiqiu/dpt-shell/files/11530973/default.zip)

**Comment by luoyesiqiu** [comment]
android10上确实有问题，晚点修复
