### ISSUE TITLE
加固完成后由于extractNativeLibs字段无法安装

### ISSUE THREAD

**Issue by SummerflyAndIce** [luoyesiqiu/dpt-shell#24]
Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]

**Comment by SummerflyAndIce** [comment]
[executable.zip](https://github.com/luoyesiqiu/dpt-shell/files/11753608/executable.zip)

**Comment by luoyesiqiu** [comment]
晚点修复
