### ISSUE TITLE
用github最新release的excutable去执行没问题,自己编译的excutable就报错 Function names and BuildId information is missing for some frames due  to unreadable libraries

### ISSUE THREAD

**Issue by yandeqing** [luoyesiqiu/dpt-shell#34]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 A  Build fingerprint: 'HUAWEI/LYA-AL00/HWLYA:10/HUAWEILYA-AL00/10.1.0.163C00:user/release-keys'
 A  Revision: '0'
 A  ABI: 'arm64'
 A  SYSVMTYPE: Maple
    APPVMTYPE: Art
 A  Timestamp: 2024-02-21 20:29:35+0800
 A  pid: 7464, tid: 7464, name: im.zuber.app  >>> im.zuber.app <<<
 A  uid: 11125
 A  signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
 A  Cause: null pointer dereference
 A      x0  0000000000000000  x1  0000007552c3a000  x2  00000000025c5d21  x3  0000007ffec2e2f0
 A      x4  00000075b201f420  x5  0000007ffec2e355  x6  000000000000002f  x7  000000000000002f
 A      x8  00000075b69fd050  x9  0000000000001000  x10 00000000ffffffff  x11 00000075c320d6a8
 A      x12 00000075c320d6c8  x13 7070612e72656275  x14 0000000000000010  x15 000000764426939a
 A      x16 000000764426ea18  x17 00000076441fecc0  x18 0000007649e74000  x19 0000007ffec2e2f0
 A      x20 00000075b699ad47  x21 00000000025c5d21  x22 0000007552c3a000  x23 0000007648e9f020
 A      x24 0000000000000004  x25 0000007648e9f020  x26 00000075c32108b0  x27 0000000000000001
 A      x28 0000007ffec2e5e0  x29 0000007ffec2e2a0
 A      sp  0000007ffec2d290  lr  00000075b69ed280  pc  00000075b69b20e0
 A  
    backtrace:
 A      NOTE: Function names and BuildId information is missing for some frames due
 A      NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
 A      NOTE: found under the lib/ directory are readable.
 A        #00 pc 000000000002e0e0  /data/data/im.zuber.app/dpt-libs/arm64/libdpt.so
 A        #01 pc 000000000006927c  /data/data/im.zuber.app/dpt-libs/arm64/libdpt.so
 A        #02 pc 00000000000653d4  /data/data/im.zuber.app/dpt-libs/arm64/libdpt.so
 A        #03 pc 0000000000062ba0  /data/data/im.zuber.app/dpt-libs/arm64/libdpt.so
 A        #04 pc 00000000000629ac  /data/data/im.zuber.app/dpt-libs/arm64/libdpt.so
 A        #05 pc 0000000000152350  /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #06 pc 00000000001495b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #07 pc 00000000001581d4  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char
    const*)+284) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #08 pc 0000000000300148  /apex/com.android.runtime/lib64/libart.so!libart.so (offset
    0x17a000) (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #09 pc 00000000002fb418  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x17a000) (bool
    art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+912) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #10 pc 00000000005d6210  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeStatic+368) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #11 pc 0000000000143994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #12 pc 000000000000153a  [anon:dalvik-classes.dex extracted in memory from /data/app/im.zuber.app-JB_f0ku0DwJWYKsgZ5FeGg==/base.apk] (com.luoyesiqiu.shell.ProxyComponentFactory.instantiateClassLoader+42)
 A        #13 pc 00000000005d3968  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeVirtual+1432) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #14 pc 0000000000143814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #15 pc 000000000021e370  /system/framework/framework.jar (android.app.LoadedApk.createOrUpdateClassLoaderLocked+1704)
 A        #16 pc 00000000005d5d04  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeDirect+1168) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #17 pc 0000000000143914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #18 pc 000000000021d704  /system/framework/framework.jar (android.app.LoadedApk.getClassLoader+12)
 A        #19 pc 00000000005d3968  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeVirtual+1432) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #20 pc 0000000000143814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #21 pc 000000000021d4be  /system/framework/framework.jar (android.app.LoadedApk.getResources+202)
 A        #22 pc 00000000005d3968  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeVirtual+1432) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #23 pc 0000000000143814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #24 pc 00000000001c773e  /system/framework/framework.jar (android.app.ContextImpl.createAppContext+150)
 A        #25 pc 00000000005d6510  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeStatic+1136) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #26 pc 0000000000143994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #27 pc 00000000001c768e  /system/framework/framework.jar (android.app.ContextImpl.createAppContext+2)
 A        #28 pc 00000000005d6510  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeStatic+1136) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #29 pc 0000000000143994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #30 pc 00000000001a5e1e  /system/framework/framework.jar (android.app.ActivityThread.handleBindApplication+1698)
 A        #31 pc 00000000005d5d04  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeDirect+1168) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #32 pc 0000000000143914  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #33 pc 00000000001a2800  /system/framework/framework.jar (android.app.ActivityThread.access$2600)
 A        #34 pc 00000000005d6510  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeStatic+1136) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #35 pc 0000000000143994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #36 pc 000000000019de5c  /system/framework/framework.jar (android.app.ActivityThread$H.handleMessage+2316)
 A        #37 pc 00000000005d3968  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeVirtual+1432) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #38 pc 0000000000143814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #39 pc 00000000003177da  /system/framework/framework.jar (android.os.Handler.dispatchMessage+38)
 A        #40 pc 00000000005d3968  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeVirtual+1432) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #41 pc 0000000000143814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #42 pc 00000000003431a0  /system/framework/framework.jar (android.os.Looper.loop+480)
 A        #43 pc 00000000005d6510  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeStatic+1136) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #44 pc 0000000000143994  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #45 pc 00000000001aaa38  /system/framework/framework.jar (android.app.ActivityThread.main+1372)
 A        #46 pc 00000000002d0a74  /apex/com.android.runtime/lib64/libart.so!libart.so (offset
    0x17a000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.2578965742566806233+320) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #47 pc 00000000005c2990  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (artQuickToInterpreterBridge+1012) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #48 pc 0000000000152468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #49 pc 00000000001495b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #50 pc 00000000001581d4  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char
    const*)+284) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #51 pc 00000000004db338  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable
    const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #52 pc 00000000004dcd60  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned
    long)+1476) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #53 pc 0000000000466b54  /apex/com.android.runtime/lib64/libart.so!libart.so (offset
    0x17a000) (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #54 pc 00000000000f8c34  /system/framework/arm64/boot.oat (art_jni_trampoline+180) (BuildId: 58d0f2797edc934ace28d647db375f1932fa70d4)
 A        #55 pc 0000000000149334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #56 pc 00000000001581b4  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char
    const*)+252) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #57 pc 0000000000300148  /apex/com.android.runtime/lib64/libart.so!libart.so (offset
    0x17a000) (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #58 pc 00000000002fb418  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x17a000) (bool
    art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+912) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #59 pc 00000000005d3658  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (MterpInvokeVirtual+648) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #60 pc 0000000000143814  /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #61 pc 0000000000408cde  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
 A        #62 pc 00000000002d0a74  /apex/com.android.runtime/lib64/libart.so!libart.so (offset
    0x17a000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.2578965742566806233+320) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #63 pc 00000000005c2990  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (artQuickToInterpreterBridge+1012) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #64 pc 0000000000152468  /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #65 pc 0000000000b2942c  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3660) (BuildId: b33f7257c2b9b8b54c0b9b01d6239f9531abe146)
 A        #66 pc 00000000001495b8  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #67 pc 00000000001581d4  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char
    const*)+284) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #68 pc 00000000004db338  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable
    const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #69 pc 00000000004dafa4  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x474000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable
    const&, _jobject*, _jmethodID*, std::__va_list)+408) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #70 pc 00000000003da540  /apex/com.android.runtime/lib64/libart.so!libart.so (offset
    0x17a000) (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+660) (BuildId: 0cc41d73c12e1e471060c8f6ba909e78)
 A        #71 pc 00000000001025c4  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+116) (BuildId: 4077d9d47e396a6c3d37d4fab9a2a047)
 A        #72 pc 0000000000105c48  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+1248) (BuildId: 4077d9d47e396a6c3d37d4fab9a2a047)
 A        #73 pc 00000000000034e0  /system/bin/app_process64 (main+1168) (BuildId: e844be217eb39b34490d3798328d1f12)
 A        #74 pc 000000000006b108  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: b91c775ccc9b0556e91bc575a2511cd0)

**Comment by yandeqing** [comment]
![image](https://github.com/luoyesiqiu/dpt-shell/assets/6889241/8b0b9fdc-eda7-4a7c-a550-912fafc11d68)
两个github库 我用的master分支

**Comment by yandeqing** [comment]
然后你的分支报错,我修改了这里
![image](https://github.com/luoyesiqiu/dpt-shell/assets/6889241/9a825a68-e70e-4b12-8c19-92e2de598761)

**Comment by luoyesiqiu** [comment]
试一下main分支

**Comment by yandeqing** [comment]
或者你可以更新最新minizip-ng的代码重新改下代码,有两个方法都变了,报错
![image](https://github.com/luoyesiqiu/dpt-shell/assets/6889241/fe20fae6-863a-4ccc-aa84-b1e9986081b2)

**Comment by luoyesiqiu** [comment]
用这个命令克隆项目，会定位到minizip项目的指定提交

**Comment by yandeqing** [comment]
果然是这样,用你这个clone 出来的项目就没问题,单独拉最新的代码就是报错
