### ISSUE TITLE
大佬更新最新的1.8.4的版本后，加固无签名的版本，apk里面dex文件丢失了，用旧版1.8.3的可以的可以

### ISSUE THREAD

**Issue by wushuangchunjun** [luoyesiqiu/dpt-shell#50]
<img width="1436" alt="image" src="https://github.com/luoyesiqiu/dpt-shell/assets/20511537/1afe3f56-49ed-44e4-887b-f8f95b67e4dd">
<img width="995" alt="image" src="https://github.com/luoyesiqiu/dpt-shell/assets/20511537/1fc855e7-8746-4247-8b1f-75a893b7fc6e">
<img width="1196" alt="image" src="https://github.com/luoyesiqiu/dpt-shell/assets/20511537/ea85fe5e-1aed-4624-8869-5d38c3765a02">

**Comment by wushuangchunjun** [comment]
一样的命令，旧版的可以在apk里面生成这个ProxyApplication，新版本的dex文件里面是空的

**Comment by luoyesiqiu** [comment]
试了几个apk都是可以的。用的是-x参数吗？加固过程中有报错吗？

**Comment by wushuangchunjun** [comment]
这个是加固后的链接: https://pan.baidu.com/s/1fdqMYYH8a4lM6kTyU8eyGg?pwd=mmta 提取码: mmta 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by wushuangchunjun** [comment]
嗯，今天我也好了，没法复现了，啥都没改动，emo了

**Comment by wushuangchunjun** [comment]
<img width="1424" alt="image" src="https://github.com/luoyesiqiu/dpt-shell/assets/20511537/17dce2a9-5ae5-4c4d-b00c-fab03f2fee09">
