### ISSUE TITLE
C++ 编译出错

### ISSUE THREAD

**Issue by SuperTizzyGod** [luoyesiqiu/dpt-shell#53]
你好
      我这里C++ 编译出错：
[CMakeError.log](https://github.com/user-attachments/files/16321048/CMakeError.log)

   用的ndk:21.4.7075529,llvm:https://android.googlesource.com/toolchain/llvm-project(a2a1e703c0edb03ba29944e529ccbf457742737b)
  电脑是：mac M2 Pro
  
  大神用的llvm 是那一个版本?,c++ 的llvm 环境怎么配置的

**Comment by luoyesiqiu** [comment]
这个项目是用Android Studio编译的
