### ISSUE TITLE
Cannot find shell files

### ISSUE THREAD

**Issue by freecode505** [luoyesiqiu/dpt-shell#56]
root@apkprotector:~# java -jar /usr/protect/executable/dpt.jar -f /root/classes.dex
2024-08-22 18:02:14.587 [main]  dpt-processor   Cannot find shell files!

Can you explain to me a little bit, is it the dex or the apk and why does this error appear? Do you want dex or apk? Can you explain to me how it works or what I'm missing?

**Comment by freecode505** [comment]
???

**Comment by luoyesiqiu** [comment]
Hello, dpt.jar should be placed in the same directory as the shell-files folder. And the -f parameter should be followed by an apk file path.

**Comment by freecode505** [comment]
tranks bro
