### ISSUE TITLE
android 15手机安装加固加签之后安装闪退。求大佬帮忙看下

### ISSUE THREAD

**Issue by wenbo-ya** [luoyesiqiu/dpt-shell#62]
![微信图片_20241018135359](https://github.com/user-attachments/assets/04cf1f1f-66ff-41f0-9f2d-bd3e309a6028)

**Comment by wenbo-ya** [comment]
原apk加固加签之后，安装到15系统，打开之后就闪退，安装到14系统打开没问题

**Comment by luoyesiqiu** [comment]
这是最新版吗？另外可以提供完整日志吗？包名可以隐去

**Comment by wenbo-ya** [comment]
[logcat.txt](https://github.com/user-attachments/files/17433256/logcat.txt)
用的最新版，
日志的包名和启动activity，这两个我用中文描述替代了

**Comment by wenbo-ya** [comment]
不好意思，确实是下载最新的时候解压之后把旧的拷进来了，最新的没问题。谢谢大佬解答
