### ISSUE TITLE
apk build help

### ISSUE THREAD

**Issue by jdjrjjde** [luoyesiqiu/dpt-shell#76]
I have a source code from this project, can you build the serverless apk file for me? Thank you
[ApkProtector.zip](https://github.com/user-attachments/files/18193034/ApkProtector.zip)
![k2](https://github.com/user-attachments/assets/91c2a8a9-9d90-4a07-8e5e-4de5889f657d)

**Comment by luoyesiqiu** [comment]
Sorry, I can't build it either.
