### ISSUE TITLE
malware with dpt-shell

### ISSUE THREAD

**Issue by 3anippon** [luoyesiqiu/dpt-shell#78]
My sister's cellphone accidentally installed an apk that steals OTP and other things, after I analyzed it there was a dpt-shell string, what is the way to find out the original base code?

**Comment by winnerawan** [comment]
> > My sister's cellphone accidentally installed an apk that steals OTP and other things, after I analyzed it there was a dpt-shell string, what is the way to find out the original base code?
> 
> It is located in the path `/data/data/[PACKAGE]/code_cache/i11111i111.zip` You need Root to access and extract
> 
> If it is convenient, please share or place the suspicious file here https://wormhole.app

I read a report from someone on
> https://mediakonsumen.com/2024/12/21/surat-pembaca/penipuan-berkedok-ktp-digital-disdukcapil

They use the the outdated official app on the Play Store (typical gov developer, outdated) and were forced to install it externally from the website below.
> https://identitaskita.com

Out of curiosity, I tried doing a bit of reverse engineering, which led me here.
sample apk
> https://wormhole.app/ALy75#XTJku1xkPKbe8xgAaB99fw
